name: Type checks and Tests (substrate-api-proxy Subschema)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  substrate_api_proxy_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.5.0

      - name: Install dependencies
        working-directory: ./subschemas/substrate-api-proxy
        run: yarn install --frozen-lockfile

      - name: Check Types
        working-directory: ./subschemas/substrate-api-proxy
        run: yarn typecheck

      - name: Run tests
        working-directory: ./subschemas/substrate-api-proxy
        run: yarn test
